### ISSUE TITLE
Add important links

### ISSUE THREAD

**Issue by ompiepy** [niyoj/mlsa-git-github-workshop#4]
Hello, @niyoj. It would be nice if important links(links shared with the participants during the session) are mentioned in the `README.md`.  

The links to be included are:
- Microsoft Learn Student Ambassadors
- Tina's Post on *"All About Microsoft Learn Student Ambassadors (MLSA)"* 
- GitHub Student Developer Pack
- Connecting to GitHub with SSH
- Learn Git Branching
- Choose a license
- Good first Issue
- GitHub Education

Can you assign this task to me.

**Comment by niyoj** [comment]
Sorry, I did some myself just now. But you can add more links if you know.

**Comment by ompiepy** [comment]
Sure.
